### PR TITLE
Regular expressions and wildcards in redirect links

### PR DESCRIPTION
**Pull request by witrin**
Add support for different matching modes:

 * `hash` uses hash to find a redirect link
 * `regex` allow regular expression in redirect links
 * `wildcard` allow wildcard expression in redirect links

The matching mode has to be set globally through the extension
option `matching_mode`.

### CODE REVIEW

**Comment by bmoex** [comment]
wow =D

**Comment by witrin** [comment]
@bmoex Did you already find the time to review the pull request?

**Comment by bmoex** [comment]
Due to includes of different composer packages the workflow need to be changed and is not possible for a TER release. 

I want to try & debug locally next week. (scheduled for friday 16 december)

**Comment by bmoex** [comment]
Hi @witrin!

I've been debugging and testing the code and was wondering why you chose two different approaches, one using the SQL query, and one using the formal-theory library. 

I've been refactoring for a coming release and found these two solutions. 

Is there a specific reason? Maybe you would like to review the refactored code too! ^^

Thanks for your work!

Kind regards,

Benjamin Serfhos

**Comment by bmoex** [comment]
Ah, I found the reason.. =)

**Comment by witrin** [comment]
Wow! I'll will try to review within the next weeks! :)

**Pull request merged**
